import { type NextRequest, NextResponse } from "next/server"

// Mock data following the schema from the attachment
const mockJobsData = {
  current_page: 1,
  data: [
    {
      id: 1,
      occupation_id: 101,
      description: "Vaga para vendedor de loja com experiência em atendimento ao cliente",
      available_jobs: 3,
      seats: 5,
      sine_id: "SINE001",
      is_cate_managed: 1,
      salary: 2500.0,
      salary_type: "monthly",
      benefits: ["Vale Transporte", "Vale Refeição", "Plano de Saúde"],
      contract_type: "CLT",
      journey: "Segunda a Sexta, 8h às 18h",
      job_type: "Presencial",
      job_scale: "Tempo Integral",
      must_job_register: 1,
      obs: "",
      status: "active",
      close_reason: null,
      active_at: new Date("2025-01-15"),
      is_meet_on_cate: 1,
      is_meet_on_company: 0,
      is_meet_tell: 1,
      company_id: 201,
      adress_id: 301,
      responsable_id: 401,
      schooling_level_id: 3,
      experience_level_id: 2,
      segment_id: 501,
      created_at: new Date("2025-01-10"),
      updated_at: new Date("2025-01-15"),
      deleted_at: null,
      closed_at: null,
      is_tech: 0,
      tech_keywords: [],
      hidden_salary: 0,
      interview_obs: "",
      same_job_location: 1,
      job_location_id: null,
      cate_responsable: "Maria Silva",
      work_regions: "Centro",
      is_online_meeting: 0,
      online_meeting_url: null,
      title: "Vendedor de Loja",
      is_company_created: 0,
      cc_status: null,
      cc_status_at: null,
      cc_reponsable_id: null,
      is_work_program_sp: 1,
      work_program: null,
      start_age: 18,
      end_age: 45,
      last_schedule_end_at: new Date("2025-02-28"),
      job_id: 1,
      used_seats_job_id: null,
      used_seats_amount: null,
      available_seats: 3,
      available_seats_kpi: 3,
      total_applications: 12,
      total_approved_applications: 2,
      expire_at: "2025-02-28",
      total_waiting_applications: 5,
      registered_by: null,
      job_location_string: "São Paulo, SP, Centro",
      schedule_seats: 5,
      responsable_creator: null,
      requirements: [],
      schedules: [],
      company: {
        id: 201,
        name: "Inova Varejo Ltda",
        fantasy_name: "Inova Varejo",
        cnpj: "12.345.678/0001-90",
        email: "contato@inovavarejo.com.br",
        phone: "(11) 3456-7890",
        created_at: new Date("2020-05-10"),
        updated_at: new Date("2025-01-10"),
      },
      experience_level: {
        id: 2,
        name: "Júnior",
        description: "Experiência de 1 a 3 anos",
      },
      occupation: {
        id: 101,
        name: "Vendedor",
        description: "Profissional de vendas",
      },
      segment: {
        id: 501,
        name: "Varejo",
        description: "Setor de varejo",
      },
      schooling_level: {
        id: 3,
        name: "Ensino Médio",
        description: "Ensino médio completo",
      },
    },
    {
      id: 2,
      occupation_id: 102,
      description: "Auxiliar administrativo para rotinas de escritório",
      available_jobs: 2,
      seats: 3,
      sine_id: "SINE002",
      is_cate_managed: 1,
      salary: 2800.0,
      salary_type: "monthly",
      benefits: ["Home Office", "Horário Flexível"],
      contract_type: "PJ",
      journey: "Segunda a Sexta, horário flexível",
      job_type: "Híbrido",
      job_scale: "Tempo Integral",
      must_job_register: 0,
      obs: "",
      status: "active",
      close_reason: null,
      active_at: new Date("2025-01-20"),
      is_meet_on_cate: 1,
      is_meet_on_company: 1,
      is_meet_tell: 1,
      company_id: 202,
      adress_id: 302,
      responsable_id: 402,
      schooling_level_id: 4,
      experience_level_id: 3,
      segment_id: 502,
      created_at: new Date("2025-01-15"),
      updated_at: new Date("2025-01-20"),
      deleted_at: null,
      closed_at: null,
      is_tech: 1,
      tech_keywords: ["Excel", "Word", "PowerPoint"],
      hidden_salary: 0,
      interview_obs: "",
      same_job_location: 1,
      job_location_id: null,
      cate_responsable: "João Santos",
      work_regions: "Copacabana",
      is_online_meeting: 1,
      online_meeting_url: "https://meet.google.com/abc-defg-hij",
      title: "Auxiliar Administrativo",
      is_company_created: 0,
      cc_status: null,
      cc_status_at: null,
      cc_reponsable_id: null,
      is_work_program_sp: 0,
      work_program: null,
      start_age: 20,
      end_age: 50,
      last_schedule_end_at: new Date("2025-03-15"),
      job_id: 2,
      used_seats_job_id: null,
      used_seats_amount: null,
      available_seats: 2,
      available_seats_kpi: 2,
      total_applications: 8,
      total_approved_applications: 1,
      expire_at: "2025-03-15",
      total_waiting_applications: 3,
      registered_by: null,
      job_location_string: "Rio de Janeiro, RJ, Copacabana",
      schedule_seats: 3,
      responsable_creator: null,
      requirements: [],
      schedules: [],
      company: {
        id: 202,
        name: "Soluções Tech Ltda",
        fantasy_name: "Soluções Tech",
        cnpj: "98.765.432/0001-10",
        email: "rh@solucoestech.com.br",
        phone: "(21) 2345-6789",
        created_at: new Date("2019-03-15"),
        updated_at: new Date("2025-01-15"),
      },
      experience_level: {
        id: 3,
        name: "Pleno",
        description: "Experiência de 3 a 5 anos",
      },
      occupation: {
        id: 102,
        name: "Auxiliar Administrativo",
        description: "Profissional de apoio administrativo",
      },
      segment: {
        id: 502,
        name: "Tecnologia",
        description: "Setor de tecnologia",
      },
      schooling_level: {
        id: 4,
        name: "Superior Incompleto",
        description: "Cursando ensino superior",
      },
    },
  ],
  first_page_url: "/api/jobs?page=1",
  from: 1,
  last_page: 1,
  last_page_url: "/api/jobs?page=1",
  links: [
    { url: null, label: "&laquo; Previous", active: false },
    { url: "/api/jobs?page=1", label: "1", active: true },
    { url: null, label: "Next &raquo;", active: false },
  ],
  next_page_url: null,
  path: "/api/jobs",
  per_page: 10,
  prev_page_url: null,
  to: 2,
  total: 2,
  sum_total_jobs: "5",
}

export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams
  const code = searchParams.get("code")

  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 500))

  // Simple validation - accept any numeric code for demo
  if (!code || !/^\d+$/.test(code)) {
    return NextResponse.json({ error: "Código inválido ou não encontrado" }, { status: 404 })
  }

  // Return mock data
  return NextResponse.json(mockJobsData)
}
